import React from 'react';
import { Link } from 'react-router-dom';
import voxaLogoDark from '@/assets/voxa-logo-dark.png';

const sections: { num: string; title: string; body: React.ReactNode }[] = [
  {
    num: "01",
    title: "About this policy",
    body: (
      <>
        This Privacy Policy applies to all personal information collected by Voxa Realty ABN [ABN] (<strong className="text-white/90">we</strong>, <strong className="text-white/90">us</strong> or <strong className="text-white/90">our</strong>) through the website at www.voxarealty.com and the Voxa Realty platform (<strong className="text-white/90">Platform</strong>).
        <br /><br />
        This policy covers two distinct groups of people whose information we handle:
        <br /><br />
        <strong className="text-white/90">Agents</strong> — real estate professionals who subscribe to the Platform and configure an AI voice assistant on their behalf.
        <br /><br />
        <strong className="text-white/90">Callers</strong> — members of the public who telephone an agent's virtual number and interact with the AI assistant. Callers do not have an account with us; their information is collected automatically as part of delivering the service to the subscribing agent.
        <br /><br />
        We are bound by the Privacy Act 1988 (Cth) and the Australian Privacy Principles (APPs). By using the Platform or calling a Voxa-powered number, you acknowledge this policy.
      </>
    ),
  },
  {
    num: "02",
    title: "Information we collect — agents",
    body: (
      <>
        When you register for and use the Platform as an agent, we collect and store the following in our database:
        <br /><br />
        <strong className="text-white/90">Account information:</strong> Full name, email address, phone number, hashed password, and account type.
        <br /><br />
        <strong className="text-white/90">Assistant configuration:</strong> Your AI assistant's name, custom prompt, first-message script, knowledge base files you upload, and assigned virtual phone number.
        <br /><br />
        <strong className="text-white/90">Subscription and billing data:</strong> Subscription tier, remaining call-minute balance, next payment date, and payment history. Payment card details are processed and held exclusively by Stripe — we do not store card numbers.
        <br /><br />
        <strong className="text-white/90">Virtual number:</strong> The virtual phone number provisioned for you via Twilio. This number is the property of Voxa Realty for the duration of your subscription (see section 08).
        <br /><br />
        <strong className="text-white/90">Google integration (optional):</strong> If you connect Google Calendar or Google Sheets, we store the resulting OAuth credentials in your account record. You may revoke this at any time (see section 09).
      </>
    ),
  },
  {
    num: "03",
    title: "Information we collect — callers",
    body: (
      <>
        When a member of the public calls a virtual number powered by Voxa, the following information is collected automatically:
        <br /><br />
        <strong className="text-white/90">Phone number:</strong> The caller's phone number as delivered by the telephone network (CLI/CLID). This is stored in our database and is visible to the subscribing agent.
        <br /><br />
        <strong className="text-white/90">Call transcript:</strong> A full text transcript of the conversation between the caller and the AI assistant, generated by Vapi and stored in our database.
        <br /><br />
        <strong className="text-white/90">Call recording:</strong> An audio recording of the call. The recording file is held on Vapi's servers (United States) and we store the URL reference in our database. Agents can access the recording through the Platform.
        <br /><br />
        <strong className="text-white/90">AI-structured outputs:</strong> The AI assistant may extract structured information from the conversation (e.g. enquiry type, property address mentioned, preferred callback time) and store this as structured data linked to the call record.
        <br /><br />
        <strong className="text-white/90">Call metadata:</strong> Call direction (inbound/outbound), duration in seconds, call end reason, and cost.
        <br /><br />
        <strong className="text-white/90">Named contacts:</strong> If the agent manually creates or edits a contact record for a caller, the name, phone number, and any notes they add are stored in our database.
        <br /><br />
        Callers are informed at the start of each call that they are speaking with an AI assistant. Agents are responsible for ensuring their first-message script also discloses that the call is being recorded, in compliance with applicable telecommunications and surveillance laws.
      </>
    ),
  },
  {
    num: "04",
    title: "Why we collect this information",
    body: (
      <>
        <strong className="text-white/90">For agents</strong> — We collect your account and configuration data to create and maintain your account, provision your virtual number, operate your AI assistant, process subscription payments, send service and billing notifications, and provide customer support.
        <br /><br />
        <strong className="text-white/90">For callers</strong> — Call transcripts, recordings, and structured outputs are collected on behalf of the subscribing agent to enable the agent to review call outcomes, follow up with prospective clients, and audit AI assistant performance. We do not use caller data for our own marketing purposes.
        <br /><br />
        <strong className="text-white/90">General</strong> — We may use aggregated, de-identified usage data (e.g. total calls handled, average call duration) to improve the Platform. No individual's information is identifiable in this analysis.
      </>
    ),
  },
  {
    num: "05",
    title: "Third-party sub-processors",
    body: (
      <>
        We rely on the following third-party services to operate the Platform. Each acts as a data processor on our behalf and is contractually bound to protect personal information:
        <br /><br />
        <strong className="text-white/90">Vapi (US)</strong> — AI voice infrastructure. Vapi processes and stores call audio and generates transcripts. Call recordings are hosted on Vapi's servers in the United States. Vapi's privacy policy is available at vapi.ai.
        <br /><br />
        <strong className="text-white/90">Twilio (US)</strong> — Virtual phone number provisioning and call routing. Twilio handles the telephone carrier layer of every inbound and outbound call. Twilio's privacy policy is available at twilio.com/legal/privacy.
        <br /><br />
        <strong className="text-white/90">MongoDB Atlas (AU/US)</strong> — Cloud database hosting. All structured data (accounts, contacts, call metadata, transcripts, assistant configuration) is stored in MongoDB Atlas. Data may reside in Australian or United States regions depending on cluster configuration.
        <br /><br />
        <strong className="text-white/90">Stripe (US)</strong> — Payment processing. Stripe collects and stores payment card details. We receive only a tokenised reference and summary billing data. Stripe's privacy policy is available at stripe.com/privacy.
        <br /><br />
        <strong className="text-white/90">Google (US) — optional</strong> — If you connect Google Calendar or Google Sheets, Google processes data in accordance with its own privacy policy at policies.google.com/privacy. This integration is optional and revocable.
        <br /><br />
        We do not sell personal information to any third party, and we do not share caller data with any party other than the subscribing agent.
      </>
    ),
  },
  {
    num: "06",
    title: "International data transfers",
    body: (
      <>
        Several of our sub-processors are based in the United States, meaning personal information is transferred internationally when we use those services:
        <br /><br />
        — Vapi receives call audio and generates transcripts (US servers).<br />
        — Twilio routes telephone calls through US infrastructure.<br />
        — Stripe processes payment data in the US.<br />
        — MongoDB Atlas may host data in US regions depending on configuration.
        <br /><br />
        Under Australian Privacy Principle 8, before we disclose personal information to an overseas recipient we must take reasonable steps to ensure the recipient does not breach the APPs in relation to that information. We satisfy this obligation through data processing agreements with each sub-processor that require them to maintain data protection standards equivalent to those required under Australian law.
        <br /><br />
        By using the Platform (as an agent) or calling a Voxa-powered number (as a caller), you acknowledge that your information may be transferred to and processed in the United States for the purposes described in this policy.
      </>
    ),
  },
  {
    num: "07",
    title: "Call recording and transcription",
    body: (
      <>
        Every call handled by the Voxa AI assistant is recorded and transcribed. This is a core feature of the Platform that enables agents to review call outcomes and follow up with prospective clients.
        <br /><br />
        <strong className="text-white/90">Storage:</strong> Audio recordings are stored on Vapi's servers in the United States. Transcripts are stored in our database (MongoDB Atlas). Both are accessible to the subscribing agent through the Platform dashboard.
        <br /><br />
        <strong className="text-white/90">Caller disclosure:</strong> The AI assistant's first message informs callers that they are speaking with an AI. Agents are required to ensure that their configured first message also informs callers that the call is being recorded. Failure to make this disclosure may breach the Telecommunications (Interception and Access) Act 1979 (Cth) and applicable state surveillance legislation. Voxa Realty is not liable for any non-compliance arising from an agent's failure to configure an appropriate first message.
        <br /><br />
        <strong className="text-white/90">Deletion:</strong> Callers who wish to request deletion of their recording or transcript may contact us at info@voxarealty.com. Upon a valid request we will delete the transcript and call record from our database and request deletion of the recording from Vapi within 14 days.
      </>
    ),
  },
  {
    num: "08",
    title: "Virtual phone numbers",
    body: "As part of the onboarding process, we purchase a virtual phone number via Twilio on the agent's behalf. The number remains the property of Voxa Realty for the duration of the subscription and is provisioned exclusively for the subscribing agent's use. Upon cancellation of a subscription, the number may be released back to Twilio's pool or reassigned. Agents should not use their Voxa virtual number as their primary business contact number if they require permanent ownership.",
  },
  {
    num: "09",
    title: "Google integration (optional)",
    body: (
      <>
        The Platform offers an optional integration with Google Calendar and Google Sheets. If you choose to connect a Google account, we store the resulting OAuth access and refresh tokens in your account record in our database.
        <br /><br />
        These credentials are used solely to perform actions you authorise (e.g. creating calendar entries, reading sheet data for the AI assistant's knowledge base). They are not shared with any third party other than Google itself.
        <br /><br />
        You may revoke this integration at any time by disconnecting it in the Platform settings or by contacting us at info@voxarealty.com. Upon revocation, all stored Google credentials are deleted from our database within 7 days. You should also revoke access in your Google account at myaccount.google.com/permissions to fully remove the authorisation.
      </>
    ),
  },
  {
    num: "10",
    title: "Data retention",
    body: (
      <>
        We retain personal information only for as long as necessary to provide the Platform and meet our legal obligations.
        <br /><br />
        <strong className="text-white/90">Active subscriptions:</strong> Agent account data, call records, transcripts, and contact records are retained for the duration of an active subscription.
        <br /><br />
        <strong className="text-white/90">After cancellation:</strong> Following cancellation of a subscription, all associated data is deleted from our database within 12 months unless you request earlier deletion.
        <br /><br />
        <strong className="text-white/90">Financial records:</strong> Billing and payment records are retained for 7 years to comply with Australian taxation law.
        <br /><br />
        <strong className="text-white/90">Deletion on request:</strong> Agents and callers may request deletion of their personal information at any time by contacting info@voxarealty.com. We will action deletion requests within 14 days. Where deletion of a record would conflict with a legal obligation (e.g. financial record keeping), we will notify you and retain only the minimum information required by law.
        <br /><br />
        <strong className="text-white/90">Vapi recordings:</strong> When we delete a call record, we also request deletion of the associated recording from Vapi. However, Vapi's own retention and deletion processes are subject to Vapi's policies and we cannot guarantee immediate deletion from Vapi's infrastructure.
      </>
    ),
  },
  {
    num: "11",
    title: "Your rights",
    body: (
      <>
        Under the Privacy Act 1988 (Cth) and the Australian Privacy Principles, you have the following rights:
        <br /><br />
        <strong className="text-white/90">Access (APP 12):</strong> You may request a copy of the personal information we hold about you. We will respond within 30 days.
        <br /><br />
        <strong className="text-white/90">Correction (APP 13):</strong> If you believe information we hold is inaccurate, out of date, incomplete, irrelevant, or misleading, you may request correction. We will action corrections within 14 days.
        <br /><br />
        <strong className="text-white/90">Deletion:</strong> You may request deletion of your personal information subject to our retention obligations (see section 10).
        <br /><br />
        <strong className="text-white/90">Callers:</strong> If you are a caller (not a registered agent) and wish to access, correct, or delete information captured during a call with a Voxa-powered number, contact us directly at info@voxarealty.com with the phone number you called from and the approximate date of the call. We will action your request within 14 days.
        <br /><br />
        To exercise any of these rights, contact us in writing at info@voxarealty.com.
      </>
    ),
  },
  {
    num: "12",
    title: "Security",
    body: (
      <>
        We implement reasonable technical and organisational measures to protect personal information against unauthorised access, disclosure, alteration, and destruction:
        <br /><br />
        — All data transmitted between your browser and our servers is encrypted using TLS 1.2 or higher.<br />
        — Passwords are stored as salted hashes — we never store or transmit plaintext passwords.<br />
        — Access to production databases is restricted to authorised personnel only.<br />
        — MongoDB Atlas provides encryption at rest using AES-256.<br />
        — Third-party sub-processors (Vapi, Twilio, Stripe) maintain their own security programs; we review their security posture before onboarding them.
        <br /><br />
        <strong className="text-white/90">Data breach notification:</strong> If we become aware of a data breach that is likely to result in serious harm, we will notify affected individuals and the Office of the Australian Information Commissioner (OAIC) as required under the Notifiable Data Breaches scheme (Privacy Act 1988, Part IIIC). We will provide details of the breach, affected data categories, and remedial steps taken.
      </>
    ),
  },
  {
    num: "13",
    title: "Complaints",
    body: (
      <>
        If you have a complaint about the way we handle your personal information, please contact us first so we can attempt to resolve it:
        <br /><br />
        Email: info@voxarealty.com<br />
        We will acknowledge your complaint within 5 business days and provide a substantive response within 30 days.
        <br /><br />
        If you are not satisfied with our response, you may lodge a complaint with the Office of the Australian Information Commissioner (OAIC):
        <br /><br />
        Website: www.oaic.gov.au<br />
        Phone: 1300 363 992<br />
        Post: GPO Box 5218, Sydney NSW 2001
      </>
    ),
  },
  {
    num: "14",
    title: "Contact us",
    body: (
      <>
        For all privacy-related enquiries, access requests, correction requests, or deletion requests:
        <br /><br />
        <strong className="text-white/90">Voxa Realty</strong><br />
        Email: info@voxarealty.com<br />
        Based in Melbourne, Victoria, Australia
        <br /><br />
        This policy was last updated in June 2025. We may update it from time to time; the current version will always be available at www.voxarealty.com/privacy-policy.
      </>
    ),
  },
];

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-[#071220] text-white">

      {/* ── Nav ── */}
      <header className="fixed inset-x-0 top-4 z-30 px-4 sm:top-6">
        <div className="mx-auto w-full max-w-5xl rounded-2xl border border-white/10 bg-[#071220]/65 shadow-[0_8px_32px_-8px_rgba(0,0,0,0.5)] backdrop-blur-[12px]">
          <div className="flex items-center justify-between gap-3 px-3 py-2 sm:px-4">
            <Link to="/" className="flex items-center gap-2">
              <img src={voxaLogoDark} alt="Voxa Realty" className="h-9 w-auto sm:h-10" />
            </Link>
            <nav className="hidden items-center gap-6 md:flex">
              <Link to="/login" className="text-sm font-semibold text-white/70 transition-colors hover:text-white">Sign In</Link>
              <Link to="/privacy-policy" className="text-sm font-semibold text-[#119c9e]">Privacy Policy</Link>
              <Link to="/voice-library" className="text-sm font-semibold text-white/70 transition-colors hover:text-white">Voice Library</Link>
            </nav>
            <Link
              to="/"
              className="inline-flex h-10 items-center rounded-xl bg-[#119c9e] px-4 text-sm font-semibold text-white hover:bg-[#0e8082]"
            >
              Book a call
            </Link>
          </div>
        </div>
      </header>

      {/* ── Page header ── */}
      <div className="relative overflow-hidden pt-36 pb-16 sm:pt-44 sm:pb-20">
        <div className="pointer-events-none absolute inset-x-0 top-0 h-full bg-[linear-gradient(to_right,rgba(20,184,166,0.05)_1px,transparent_1px),linear-gradient(to_bottom,rgba(20,184,166,0.05)_1px,transparent_1px)] bg-[size:40px_40px]" />
        <div className="pointer-events-none absolute left-[-10%] top-[-10%] h-[28rem] w-[28rem] rounded-full bg-teal-500/10 blur-[100px]" />
        <div className="mx-auto max-w-5xl px-6 lg:px-10">
          <p className="text-[0.68rem] font-bold uppercase tracking-[0.32em] text-[#119c9e]">Legal</p>
          <h1 className="mt-4 text-4xl font-semibold leading-tight tracking-tight text-white sm:text-5xl">
            Privacy Policy
          </h1>
          <p className="mt-4 max-w-xl text-sm leading-6 text-sky-100/60">
            This policy covers both agents who subscribe to the Voxa Realty platform and callers who interact with Voxa-powered phone numbers. Last updated June 2025.
          </p>
        </div>
      </div>

      {/* ── Content ── */}
      <main className="mx-auto max-w-5xl px-6 pb-24 lg:px-10">
        <div className="divide-y divide-white/[0.06]">
          {sections.map((s) => (
            <div key={s.num} className="grid gap-6 py-10 lg:grid-cols-[220px_1fr] lg:gap-16">
              <div className="flex items-start gap-3">
                <span className="shrink-0 text-xs font-bold tracking-widest text-[#119c9e]/70">{s.num}</span>
                <h2 className="text-base font-semibold leading-snug tracking-tight text-white">{s.title}</h2>
              </div>
              <div className="text-sm leading-7 text-sky-100/60">
                {s.body}
              </div>
            </div>
          ))}
        </div>
      </main>

      {/* ── Footer ── */}
      <footer className="border-t border-white/[0.06] bg-[#071220] px-6 py-5 lg:px-10">
        <div className="mx-auto flex flex-col md:flex-row max-w-5xl items-center justify-between gap-3 text-center md:text-left text-xs text-white/30 sm:text-sm">
          <p className="font-semibold text-white/50">Voxa Realty</p>
          <p>AI receptionist and sales agent software for real estate teams.</p>
          <Link to="/privacy-policy" className="hover:text-white/60 transition-colors">Privacy Policy</Link>
        </div>
      </footer>

    </div>
  );
};

export default PrivacyPolicy;
